### ISSUE TITLE
[important] [security] 加载自身将会耗尽操作系统资源

### ISSUE THREAD

**Issue by kudos5566** [4ra1n/super-xray#112]
- 你的操作系统是：Windows
- 你的xray版本是：xray_windows_amd64.exe1.9.3
- 你的super-xray版本是：1.2
- 你选择的xray文件选择super-xray自身exe将会无限循环启动
- 能够附带截图更佳

**Comment by 4ra1n** [comment]
@kudos5566 
感谢反馈。
看起来这个问题并不影响使用是吗？你的意思是如果选择了super-xray自己会出问题，但如果选择正确的xray是没问题的，是否是这样的？

**Comment by 4ra1n** [comment]
选择xray文件功能没办法限制，因为我没办法知道你选择的是真正的xray，除非解析二进制文件，但这就杀鸡用牛刀了。所以说输入什么文件应该由用户自己决定

**Comment by 4ra1n** [comment]
@kudos5566 非常感谢指出这个安全问题，我已经在本地复现，这不仅会导致`super-xray`不可用，而且很可能导致`Windows`系统资源耗尽，我会尽快处理并发布修复版本。

**Comment by Ludovicofu** [comment]
对，崩了，我现在就用不了super_xray了

**Comment by 4ra1n** [comment]
@Ludovicofu 这个问题已经修复，但是还没有打包发release，我会在明后天发布。只要你不选择`super-xray`本身的话就没问题，你选择正确的`xray`即可。

**Comment by 4ra1n** [comment]
@Ludovicofu @kudos5566  感谢你们的贡献，已经发布新版本1.3，修复了这个问题
