### ISSUE TITLE
[feat] 加入六款小游戏用于摸鱼

### ISSUE THREAD

**Issue by 4ra1n** [4ra1n/super-xray#124]
贪吃蛇：https://github.com/hexadeciman/Snake
Flappy Bird：https://github.com/jiashunx/games-flappybird
扫雷：https://github.com/BlankSpacePlus/java-mine-sweeper
弹球：https://github.com/BlankSpacePlus/java-pinball
斗地主：https://github.com/ljheee/PlayCard
雷电：https://github.com/Hph1998/ThunderGame

**Comment by 4ra1n** [comment]
1.3

**Comment by 12qwertyuiop** [comment]
你是懂摸鱼的
