### ISSUE TITLE
[bug]没有自动生成plugin，ca， module 等等文件

### ISSUE THREAD

**Issue by shanzhengliu** [4ra1n/super-xray#129]
- 你的操作系统是：Windows
- 你的xray版本是：xray_windows_amd64.exe
- 你的super-xray版本是：1.3

如标题。试了jar和exe版都不行

**Comment by 4ra1n** [comment]
检查下是否是最新版xray(1.9.4)
然后尝试重启，应该可以解决
如果多次重启还是不行的话，删除当前目录的super-xray.db再重试
暂时不要把xray和super-xray放在同一个目录，分开放

如果以上做法都无法解决问题，可以再和我说下，我查看原因

**Comment by shanzhengliu** [comment]
问题感觉是当前目录没有生成super-xray.db

**Comment by 4ra1n** [comment]
你这个问题我在两台windows电脑上都尝试了，并且让朋友也测试多次，没有出现问题，所以我可能无法解决了，看看有没有其他人遇到。

super-xray.db的逻辑是：保存你选择的xray路径，每次启动的时候自动加载，如果不存在这个问题，那其实也正常，只要你手动选择加载一次就会保存了。

感谢！
