### ISSUE TITLE
[feat] 被动扫描允许自由设置（目前仅支持127）

### ISSUE THREAD

**Issue by Ludovicofu** [4ra1n/super-xray#131]
- 你的操作系统是：Windows
- 你的xray版本是：xray_windows_amd64.exe 以及具体版本如1.9.4
- 你的super-xray版本是：例如1.3
- 你的问题是什么情况下发生的
- 能够附带截图更佳
burp代理
![image](https://user-images.githubusercontent.com/91811209/213102761-023c1bfe-3d68-4b4f-96ae-e1d9abd70c1e.png)
super_xray代理
![image](https://user-images.githubusercontent.com/91811209/213102842-40428e4a-63d9-4209-a487-1ddd30fc5735.png)
测试页面显示
![image](https://user-images.githubusercontent.com/91811209/213102983-92ecd66a-82ea-4f5b-98f9-60236fdc61dc.png)
super_xray输出
![image](https://user-images.githubusercontent.com/91811209/213102913-02702353-694b-4c10-83fa-c102d1e53995.png)
单用xray被动扫描则不会出现此情况
![image](https://user-images.githubusercontent.com/91811209/213104007-66726eff-6f2f-41ef-b63d-f71186bfce84.png)

**Comment by Ludovicofu** [comment]
![image](https://user-images.githubusercontent.com/91811209/213103925-18932c3b-9dd7-4037-8483-6c091c861381.png)

**Comment by 4ra1n** [comment]
你这个问题我复现了，你不应该设置上面的代理：
![image](https://user-images.githubusercontent.com/34726933/213103911-eede5ef0-2a5f-41eb-8b7c-5f0ce5502100.png)

直接输入一个8081端口点击启动就行了

解决办法：
![image](https://user-images.githubusercontent.com/34726933/213104009-1f5269ae-a610-45d3-91a2-424b0866490c.png)

**Comment by 4ra1n** [comment]
上面的那个代理配置不是被动扫描的代理，是http的代理

**Comment by Ludovicofu** [comment]
已解决

**Comment by Ludovicofu** [comment]
只能监听本地的端口吗？

**Comment by 4ra1n** [comment]
绝大多数情况下监听都应该是`127.0.0.1:port`

如果确实有这个需求，我考虑加一下

**Comment by Ludovicofu** [comment]
有这个需要

**Comment by 4ra1n** [comment]
1.4
