### ISSUE TITLE
[bug] Super-Xray.app 闪退

### ISSUE THREAD

**Issue by KlinKlinKlin** [4ra1n/super-xray#147]
- 你的操作系统是：Linux/Windows/MacOS 以及什么版本
- mac
- 你的xray版本是：xray_windows_amd64.exe 以及具体版本如1.9.4
- 你的super-xray版本是：例如1.3
- 1.5
- 你的问题是什么情况下发生的
- 双击打开闪退
- 能够附带截图更佳

**Comment by 4ra1n** [comment]
MAC OS版也需要本地有Java环境的，目前APP不稳定，需要更多测试

**Comment by KlinKlinKlin** [comment]
本地 是有java环境的   建议学习burp的那种方式 自带jre 然后就不会崩溃了

**Comment by JE2Se** [comment]
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600001191920 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

本地默认是1.8版本的java，这个跟java的版本有关系吗，在应用内直接java-jar可以启动，直接app打不开，感谢作者分享

**Comment by 4ra1n** [comment]
@JE2Se 对java版本没有要求，这个应该是我对Mac OS不熟悉，打包的问题，直接用java -jar启动吧，如果你熟悉MAC OS，可以自行制作一个可用的APP

**Comment by JE2Se** [comment]
辛苦作者回答，我的是最新系统的amd版本的，
如果直接java -jar起就没问题。-jar启动下载会下载到super-xray同目录，程序就能读取，
我这边使用了jar2app进行打包，点击xray下载面板后，下载卡百分之3，但是如果在jar2app制作的app下载路径是上层目录，程序无法加载，如果强行拖拽过去，点击加载，xray会把配置文件生成到我的~目录里面，导致xray无法运行
请问一下作者是用什么方法打包的app，我这边尝试一下

**Comment by 4ra1n** [comment]
@JE2Se 这个其实我忘记了，我好像是参考了其他某个App，基于java -jar启动的，你可以自行查找下，我忘记了

**Comment by KlinKlinKlin** [comment]
其实如果不为了压缩 应用可以选择 将java环境打包到app里面 这样就不会受到 电脑本身的java环境所导致的问题。至少burp是这么解决的.
