### ISSUE TITLE
[feat] radium support file input

### ISSUE THREAD

**Issue by enomothem** [4ra1n/super-xray#148]
## rad 支持文件

目前1.5.0 版本仅支持单个url，无法对多个目标进行联动。
增加采用文件导入功能，对目标遍历读取。

## rad 支持拖拽

目前1.5.0版本仅支持xray的拖拽，rad无法拖拽，当然也不是很重要，可忽略。

**Comment by 4ra1n** [comment]
@enomothem 感谢反馈问题，我有空看一下

**Comment by 4ra1n** [comment]
我已经支持了rad文件拖拽的功能，但是rad好像没有输入多个url同时跑的功能

**Comment by 4ra1n** [comment]
@enomothem 
给出的一种解决办法：可以导出批量文件
https://github.com/4ra1n/super-xray/issues/155

**Comment by 4ra1n** [comment]
1.6

**Comment by enomothem** [comment]
感谢师傅对我建议的关注，我有一种想法，就是直接使用for循环实现在super-xray里对文件读取。  
一般Rad平时我是使用以下命令单独开一个窗口，然后xray进行监听：

```
for /f  %i in (target.txt) do (rad_windows_amd64.exe -t %i --http-proxy 127.0.0.1:7777) 
```
要是能把这条命令内置到super-xray的rad模块中，我就不需要另外单独开一个窗口执行命令，这样就舒服多了。
