### ISSUE TITLE
[feat] request 支持自定义 user-agent

### ISSUE THREAD

**Issue by Vip4pt** [4ra1n/super-xray#149]
## 因为不清楚格式，还有实在是再配置中照不到useragent的设置
...

**Comment by 4ra1n** [comment]
不太清楚你提到的request格式是什么意思，可以进一步解释吗？

关于useragent头不需要自行配置，已经内置，模拟正常浏览器，是有什么特殊的需求吗？

**Comment by 4ra1n** [comment]
1.6
