### ISSUE TITLE
[feat] 允许设置请求Cookie内容

### ISSUE THREAD

**Issue by G-H-Z** [4ra1n/super-xray#150]
## 为什么需要这个功能
...xray基于爬虫，应该设置基于cookie登录爬虫扫描，因为我安装了superxray，xray的config配置文件会自动转到superxray下，在superxray下并无找到有关cookie配置，且强烈建议superxray应保留xray目录本来的config.yaml

**Comment by 4ra1n** [comment]
提了另外一个issue，保留xray目录原来的config.yaml文件

**Comment by 4ra1n** [comment]
1.6
