### ISSUE TITLE
[important] 给RAD联动提供一种批量执行的办法

### ISSUE THREAD

**Issue by 4ra1n** [4ra1n/super-xray#155]
RAD自身无法对批量目标进行扫描，所以我只能通过输入的批量文件，导出一份命令，可以自行执行来实现批量的功能

**Comment by 4ra1n** [comment]
1.6

**Comment by luckluchen** [comment]
也许可以通过参考Python脚本来完善这个问题
脚本如下
https://github.com/timwhitez/rad-xray
