### ISSUE TITLE
[security] 避免使用 777 权限

### ISSUE THREAD

**Issue by imlonghao** [4ra1n/super-xray#25]
https://github.com/4ra1n/super-xray/blob/1569c5c/src/main/java/com/chaitin/xray/utils/ExecUtil.java#L13

在非 Windows 下，会把 xray 主程序权限设置为 777，任何人都可以读写，低权限用户可以替换掉 xray 进行权限提升

**Comment by 4ra1n** [comment]
@imlonghao 感谢，我会修改

**Comment by 4ra1n** [comment]
0.3-beta
