### ISSUE TITLE
[未知bug] open module.xray.yaml: access is denied

### ISSUE THREAD

**Issue by Le1a** [4ra1n/super-xray#35]

**Comment by 4ra1n** [comment]
@Le1a 这个问题我测试没有遇到过。猜测是权限原因
有没有更多的信息，比如super-xray版本，jdk版本，操作系统，xray版本

**Comment by Le1a** [comment]
我换成386架构的就能用了 嘻嘻

**Comment by 4ra1n** [comment]
嗯，逻辑是先删除所有当前的配置文件，然后重新生成一遍，复制两份到当前目录和xray目录。因为xray有一点小bug被迫这样来做。这个问题我也不知道怎么解决，看看后面其他师傅会不会也遇到吧

**Comment by Le1a** [comment]
然后遇到的问题就是...他删除了配置文件，但并没有生成一份配置文件 所以爆了一个配置文件的错误

**Comment by Le1a** [comment]
貌似发现问题了，因为xray1.9.3版本不止生成一个配置文件，还包括module.xray.yaml ，plugin.xray.yaml，xray.yaml。在用工具去加载xray的时候，删除了这些配置文件，但只生成了一个config.yaml。于是会爆缺少另外三个配置文件缺少/权限不足 的错误。

**Comment by 4ra1n** [comment]
嗯，你可以下载最新的试试，工具目前没有兼容1.9.3版本以外的版本

**Comment by Le1a** [comment]
就是最新版 1.9.3的问题 在老版本当中 的确是只有一个config.yaml配置文件，我用1.8.4是能正常使用的

**Comment by Le1a** [comment]
貌似这个bug 只存在于最新版的xray_windows_amd64.exe当中

**Comment by 4ra1n** [comment]
嗯，昨天我测试，环境是win11+jdk9/11/17+xray_windows_amd64.exe 1.9.3，没有问题，今晚我再确认下吧

**Comment by 4ra1n** [comment]
我测试了下，在`Win11`+`JDK19`+`xray_windows_amd64.exe`的1.9.3版本跑`0.4-beta`是正常的，你那边可以再试试。
![图片](https://user-images.githubusercontent.com/34726933/203299859-aa0e980c-1187-4e9b-886b-5372fa9a45c2.png)

**Comment by Le1a** [comment]
Win11 + JDK11 + xray_windows_amd64.exe的1.9.3版本 就有问题，我朋友用的JDK10 也出现了同样的问题，maybe是JDK版本的问题，我换一个版本试试

**Comment by Le1a** [comment]
![image](https://user-images.githubusercontent.com/97610822/203303456-a3a89594-5def-43ba-a06b-59687aa1ac4c.png)

**Comment by 4ra1n** [comment]
好的，我再多测试看看

**Comment by Le1a** [comment]
好了，发现问题了，因为我之前都是双击打开的jar包，现在使用命令行就可以了.....

**Comment by 4ra1n** [comment]
好的，感谢。我会在readme里加上这个，以防止其他师傅遇到
