### ISSUE TITLE
[important] 反连平台没有设置remote_server为true

### ISSUE THREAD

**Issue by SkinAir** [4ra1n/super-xray#57]
- 你的操作系统是：Windows
- 你的xray版本是：xray_windows_amd64.exe 以及具体版本如1.9.3
- 你的super-xray版本是：0.6-beta
- 设置反连平台未正确开启"true"，需手动修改
![1669255092566](https://user-images.githubusercontent.com/71880910/203677231-39005540-d73b-4d2d-8fb4-c68e185934f9.jpg)
- 每次退出super-xray自动删除config.yaml，无法保存config文件
![image](https://user-images.githubusercontent.com/71880910/203677626-1f1a8f57-89c5-4b29-81d6-e2543977e872.png)

**Comment by 4ra1n** [comment]
@SkinAir 感谢，这个issue我会改为反连平台没有true。然后另开一个issue为保存上次配置文件。目前如果要使用反连，可以暂时先手动改成true，我尽快处理吧。

**Comment by 4ra1n** [comment]
对了，图中第一处http enabled选项，应该是由独立的反连平台设置的。

作为开启扫描的客户端，应该开启的是client的remote_server为true，这里确实有问题。

通常建议是开启独立的，而不是自带的，独立的平台是跑在服务端没有界面的，所以没必要专门做这个功能。

对于比较小众的反连+扫描客户端一体的，暂时不打算做，因为用的人不多且不推荐这样使用。

**Comment by 4ra1n** [comment]
不过我会考虑加个功能，简单填写配置后，导出一份适用于反连平台的配置文件，然后直接`./xray reverse`就可以启动

**Comment by SkinAir** [comment]
> 对了，图中第一处http enabled选项，应该是由独立的反连平台设置的。
> 
> 作为开启扫描的客户端，应该开启的是client的remote_server为true，这里确实有问题。
> 
> 通常建议是开启独立的，而不是自带的，独立的平台是跑在服务端没有界面的，所以没必要专门做这个功能。
> 
> 对于比较小众的反连+扫描客户端一体的，暂时不打算做，因为用的人不多且不推荐这样使用。

感谢纠正🥠

**Comment by 4ra1n** [comment]
0.7版本已更新，支持JDK8且提供EXE
