### ISSUE TITLE
优化启动脚本

### ISSUE THREAD

**Issue by killpi** [4ra1n/super-xray#60]
平时使用的工具大多为java8，修改了下bat，设置临时的java11启动，但是会有cmd窗口不能关闭，不知道这个能否解答下。
@echo off
set JAVA_HOME="D:\env\java11"
set CLASSPATH=.;%JAVA_HOME%\lib\dt.jar;%JAVA_HOME%\lib\tools.jar;
set Path=%JAVA_HOME%\bin;
java -jar super-xray-0.6-beta.jar

**Comment by 4ra1n** [comment]
@killpi 你提到的这个cmd窗口不能关闭，关掉ui或者cmd窗口的时候，应该会等待几秒才能关闭，因为我设置了一个功能：程序关闭的时候删除一些零时文件，并且等待所有进程退出，然后再关闭，所以你这里需要等待几秒。

**Comment by killpi** [comment]
其实我想说的是感觉启动后有个cmd不能关闭看着很不得劲，不过刚刚我参考了下burp的启动，创建vbs脚本：
set ws=createobject("wscript.shell")
ws.Run """start.bat""",0
可以做到没有cmd窗口直接启动

**Comment by 4ra1n** [comment]
赞！你可以测试下这样会不会出其他bug，因为之前有师傅反馈不通过命令行`java -jar`启动的话会有权限问题

**Comment by 4ra1n** [comment]
0.7 版本已支持JDK8，且包含了EXE版本
