### ISSUE TITLE
[important] [公告] CPU消耗过高问题的解决

### ISSUE THREAD

**Issue by komomon** [4ra1n/super-xray#69]
- 你的操作系统是：window
- 你的xray版本是：xray_windows_amd64.exe 1.9.3
- 你的super-xray版本是：例如0.7
运行一次后任务是结束了，但是主程序占用cpu一直降不下来，，，，**高的有点太离谱**
![image](https://user-images.githubusercontent.com/52700174/204092354-f1f2be46-8abf-4003-94c5-4aef07145889.png)

**Comment by 4ra1n** [comment]
感谢反馈，我查一下原因

**Comment by 4ra1n** [comment]
@komomon 我排查了应该是你没有点击左下角终止，也就是说虽然扫描完成了，但你还是需要点击强制停止的，点击后CPU立马就会降下来。可以试试。这个问题我会在下个版本修复，目前可以这样手动解决。如果这样还是无法解决，可以再留言

**Comment by komomon** [comment]
> @komomon 我排查了应该是你没有点击左下角终止，也就是说虽然扫描完成了，但你还是需要点击强制停止的，点击后CPU立马就会降下来。可以试试。这个问题我会在下个版本修复，目前可以这样手动解决。如果这样还是无法解决，可以再留言

可以了，感谢

**Comment by 4ra1n** [comment]
0.8版本添加了停止按钮解决
