### ISSUE TITLE
MacOSX 加载xray时无法成功

### ISSUE THREAD

**Issue by TheCryingGame** [4ra1n/super-xray#74]
- 你的操作系统是：MacOS 10.15.7 (19H15)
- 你的xray版本是：xray_darwin_amd64 1.9.3
- 你的super-xray版本是：0.8
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/48227194/205471572-ed553b58-5bae-45e1-9b59-488fc8bbaf10.png">

我是把jar打包成了app文件，之后在其他文件夹下加载xray，然鹅一直不生效，我把xray复制到app文件夹里也不行

**Comment by 4ra1n** [comment]
@TheCryingGame 你好，有试过java -jar启动是否有问题吗

**Comment by TheCryingGame** [comment]
> 
这个是没有问题的

**Comment by 4ra1n** [comment]
@TheCryingGame 这个问题大概的原因是App没有权限创建文件，我之后看一下能不能解决，你可以先java -jar用

**Comment by TheCryingGame** [comment]
> @TheCryingGame 这个问题大概的原因是App没有权限创建文件，我之后看一下能不能解决，你可以先java -jar用

好的
