### ISSUE TITLE
突然报了一个这个错误。

### ISSUE THREAD

**Issue by JK1706** [4ra1n/super-xray#95]
- 你的操作系统是：Windows
- 你的xray版本是：xray_windows_amd64.exe 1.9.3
- 你的super-xray版本是：1.1
- 你的问题是什么情况下发生的
- 加载config.yaml的时候
- 能够附带截图更佳
- 
![image](https://user-images.githubusercontent.com/72113877/211719797-b9e31cef-cf51-42f8-a6f4-86edc6f0343e.png)

**Comment by 4ra1n** [comment]
@JK1706 
因为xray更新了1.9.4版本，配置文件和之前的有区别了，可以下载最新版试试
（super-xray有一个下载面板，你可以直接在那里下载最新的1.9.4版本）
